### ISSUE TITLE
Icon source maps missing

### ISSUE THREAD

**Issue by davekiss** [danielkov/react-ikonate#20]
Hey, thanks for putting this lib together.

I'm getting errors in my console during build that source maps are missing from the npm package for every icon.

`⚠️  Could not load source file "../../../src/icons/Timer.tsx" in source map of "../../../node_modules/react-ikonate/dist/esm/icons/Timer.js".`

Looks like the `src` dir is not shipped with the npm package. In this case, perhaps remove source maps from the npm build entirely, or add the src?

Cheers

**Comment by danielkov** [comment]
@davekiss thanks for bringing this up.

There are three approaches I can take with this:
1. Copy over sources to `dist` and resolve source map paths.
2. Drop source maps altogether.
3. Add `src` folder to package deployed to NPM.

I don't personally like 1. Do you find there is a benefit to having source maps or should I just drop support to it altogether?

**Comment by davekiss** [comment]
@danielkov I don't see a benefit to source maps for this library, but if you do I'd say 3, otherwise 2

**Comment by danielkov** [comment]
Release `2.0.1` fixes this by removing source maps. Check out #28 for reference.
